# Generated by Django 5.1 on 2024-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('subjects', models.CharField(choices=[('ARTS', 'Arts'), ('BUS', 'Business'), ('GEO', 'Geography'), ('ENGR', 'Engineering'), ('HEALTH_MED', 'Health and Medicine'), ('HIST', 'History'), ('LAW_POL', 'Law and Politics'), ('LANG_CULT', 'Languages and Cultures'), ('MATH', 'Mathematics'), ('PHIL', 'Philosophy'), ('SCI', 'Science'), ('SOC_SCI', 'Social Sciences'), ('TECH', 'Technology'), ('WRIT_LIT', 'Writing and Literature')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
