# Generated by Django 5.1.3 on 2025-01-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyset',
            old_name='subjects',
            new_name='subject',
        ),
    ]
