# Generated by Django 5.1.2 on 2024-11-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysetapp', '0002_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studyset_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='studysetapp.studyset')),
            ],
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
