# Generated by Django 5.1.2 on 2024-11-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('learner_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresult', to='accountapp.learner')),
                ('studyset_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresult', to='studysetapp.studyset')),
            ],
        ),
    ]
