# Generated by Django 5.1.2 on 2024-11-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='learner_id',
            new_name='learner_instance',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='studyset_id',
            new_name='studyset_instance',
        ),
    ]
