# Generated by Django 5.1.2 on 2024-11-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_rename_learner_id_testresult_learner_instance_and_more'),
        ('testapp', '0003_alter_generatedtest_learner_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='learner_instance',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='studyset_instance',
        ),
        migrations.AddField(
            model_name='testresult',
            name='generated_test_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.generatedtest'),
        ),
    ]
