# Generated by Django 5.1.2 on 2024-11-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0003_remove_testresult_learner_instance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='overall_score',
            new_name='number_of_questions',
        ),
    ]
