# Generated by Django 5.1.2 on 2024-11-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_rename_overall_score_testresult_number_of_questions'),
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='generated_test_instance',
        ),
        migrations.AddField(
            model_name='testresult',
            name='studyset_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studysetapp.studyset'),
        ),
    ]
