# Generated by Django 5.1.2 on 2024-11-10 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcardapp', '0001_initial'),
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('flashcard_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardapp.flashcard')),
                ('studyset_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studysetapp.studyset')),
            ],
        ),
    ]
