# Generated by Django 5.1.2 on 2024-11-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0001_initial'),
        ('flashcardapp', '0004_rename_studyset_id_pdf_studyset_instance'),
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='flashcardapp.flashcard')),
                ('learner_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.learner')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='flashcardapp.flashcard')),
                ('studyset_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studysetapp.studyset')),
            ],
        ),
    ]
