# Generated by Django 5.1.2 on 2024-11-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0004_rename_studyset_id_pdf_studyset_instance'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtest',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='generatedtest',
            name='question',
        ),
        migrations.AddField(
            model_name='generatedtest',
            name='flashcard_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardapp.flashcard'),
        ),
    ]
