# Generated by Django 5.1.2 on 2024-11-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
        ('studysetapp', '0001_initial'),
        ('testapp', '0002_remove_generatedtest_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedtest',
            name='learner_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountapp.learner'),
        ),
        migrations.AlterField(
            model_name='generatedtest',
            name='studyset_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studysetapp.studyset'),
        ),
    ]
