# Generated by Django 5.1.2 on 2024-11-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_generatedtest_learner_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtest',
            name='learner_instance',
        ),
    ]
