# Generated by Django 5.1.2 on 2024-11-03 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_generatedtest_learner_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtest',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
