# Generated by Django 5.1 on 2024-11-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flashcard_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studyset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='studysetapp.studyset')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studyset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='studysetapp.studyset')),
            ],
        ),
    ]
