# Generated by Django 5.1.3 on 2024-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
