# Generated by Django 5.1.2 on 2024-11-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0001_initial'),
        ('studysetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcards',
            new_name='Flashcard',
        ),
    ]
