# Generated by Django 5.1.2 on 2024-11-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0002_rename_flashcards_flashcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='studyset_id',
            new_name='studyset_instance',
        ),
    ]
