# Generated by Django 5.1.2 on 2024-11-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0003_rename_studyset_id_flashcard_studyset_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='studyset_id',
            new_name='studyset_instance',
        ),
    ]
