# Generated by Django 5.1.2 on 2024-11-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardapp', '0004_rename_studyset_id_pdf_studyset_instance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
